# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tokkonopapa.github.com/Initializr2-on-jekyll/
title: サイトのタイトル
author: tokkonopapa

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Analytics
google_analytics_tracking_id: UA-20543951-2